[package]
name = "rost"
version = "0.1.0"
authors = ["Joel Speitelsbach <joel.speitelsbach@gmail.com>"]

[dependencies]

[dependencies.sdl2]
version = "0.29.1"
default-features = false
features = ["ttf","image","gfx","mixer"]
