[package]
name = "joel"
version = "0.1.0"
authors = ["Joel Speitelsbach <joel.speitelsbach@gmail.com>"]

[[bin]]
name = "joel"
path = "mod.rs"

[dependencies]
serde = ""
serde_derive = ""
bincode = ""
